### PR TITLE
fixed the alignment in home page,

### PR DESCRIPTION
**Pull request by giri3sg**
removed unnecessary code.

### CODE REVIEW

**Comment by pkpio** [comment]
Yo! Giri already on it :)

Best,
Praveen
https://pkp.io

**Comment by giri3sg** [comment]
haha :+1:  i checked it and it does't have any side effects.
I think it would be nice to send pull req, so that u will know where and what code I'm changing , just to be sure we are on same page :)

**Comment by pkpio** [comment]
Hmm. That sounds like a good idea.

**Comment by pkpio** [comment]
Problem with layout of course result page

**Pull request merged**
